# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 01:46
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
