# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170311_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='abstract',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ranking',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
